### PR TITLE
[FIX]: App crashes when search * (asterisk) in member list (#6427)

### LINKED ISSUE #6427: bug: App crashes when search * (asterisk) in member list
### Describe the Bug

When you go inside channel members view and type * in the search box the app crashes

### Steps to Reproduce

1. go to any channel
2. Open the members list
3. Try to search * (asterisk)

### Expected Behavior

The app should not crash atleast 

### Actual Behavior

The app crashes 

### Rocket.Chat Server Version

7.8.0

### Rocket.Chat App Version

4.61.0.80987

### Device Name

One plus nord ce3

### OS Version

Android 15

### Additional Context

https://github.com/user-attachments/assets/eb03c1bd-1fdf-4a93-b022-5bbf37381c29

### PR DESCRIPTION
**Pull request by luckyjsx**
## Proposed changes

This pull request fixes a bug where the app crashes when an asterisk (*) is entered into the member list search bar. The crash was due to the * being treated as an unescaped regex character in the search logic. The solution involves sanitizing the input to properly handle special characters.

## Issue(s)	

Closes #6427

## How to test or reproduce

a)Open any channel in the app.
b)Tap on the member list to view channel members.
c)Enter an asterisk (*) into the search bar.
d)The app should not crash, and input should be handled safely.

## Types of changes

- [x ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [ x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/lib/methods/helpers/helpers.ts [hunk 1]
```diff
@@ -7,6 +7,8 @@ export function isGroupChat(room): boolean {
 	return ((room?.uids && room.uids.length > 2) || (room?.usernames && room.usernames.length > 2)) ?? false;
 }
 
+export const escapeRegExp = (string: string) => string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
```
Comment (diegolmello) [inline app/lib/methods/helpers/helpers.ts]: Can you test if `sanitizeLikeString` fix it?
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/c45cb0aacdd33b41be454b25651b02947b39b0e6/app/lib/database/utils.ts#L6

If it doesn't, we need to move this to the same place and write tests

File: app/views/RoomMembersView/index.tsx [hunk 2]
```diff
@@ -380,12 +380,15 @@ const RoomMembersView = (): React.ReactElement => {
 		}
 	};
 
-	const filteredMembers =
+		const filteredMembers =
```
Comment (diegolmello) [inline app/views/RoomMembersView/index.tsx]: Looks like unnecessary change.
Run `yarn prettier-lint`

**Review by diegolmello — DISMISSED** [review]
Thanks for your contribution!

Looking good, but I miss more information about the bug itself.
Why does it happen?

File: app/lib/methods/helpers/helpers.ts (hunk 1 above)
Comment (luckyjsx) [reply app/lib/methods/helpers/helpers.ts]: it's working good with sanitizeLikeString

File: app/views/RoomMembersView/index.tsx (hunk 2 above)
Comment (luckyjsx) [reply app/views/RoomMembersView/index.tsx]: thanks for this suggestion

**Comment by luckyjsx** [comment]
@diegolmello please review this pr

File: app/views/RoomMembersView/index.tsx [hunk 3]
```diff
@@ -382,10 +383,10 @@ const RoomMembersView = (): React.ReactElement => {
 
 	const filteredMembers =
 		state.members && state.members.length > 0 && state.filter
-			? state.members.filter(
-					m =>
-						m.username.toLowerCase().match(state.filter.toLowerCase()) || m.name?.toLowerCase().match(state.filter.toLowerCase())
-			  )
+			? state.members.filter(m => {
+					const filter = sanitizeLikeString(state.filter.toLowerCase()) ?? '';
+					return m.username.toLowerCase().match(filter) || m.name?.toLowerCase().match(filter);
```
Comment (OtavioStasiak) [inline app/views/RoomMembersView/index.tsx]:
```suggestion
			? state.members.filter(m => {
					const filter = sanitizeLikeString(state.filter.toLowerCase()) || '';
					return m.username.toLowerCase().match(filter) || m.name?.toLowerCase().match(filter);
```

`||` handles all falsy values (including empty string), while `??` only handles null or undefined. In this case, we want to cover all falsy cases.

File: app/views/RoomMembersView/index.tsx [hunk 4]
```diff
@@ -382,10 +383,10 @@ const RoomMembersView = (): React.ReactElement => {
 
 	const filteredMembers =
 		state.members && state.members.length > 0 && state.filter
-			? state.members.filter(
-					m =>
-						m.username.toLowerCase().match(state.filter.toLowerCase()) || m.name?.toLowerCase().match(state.filter.toLowerCase())
-			  )
+			? state.members.filter(m => {
+					const filter = sanitizeLikeString(state.filter.toLowerCase()) ?? '';
```
Comment (OtavioStasiak) [inline app/views/RoomMembersView/index.tsx]: We should move the `const filter` out of the `.filter()` method, moving it outside of .filter() avoids calling it repeatedly for every member. This improves performance by running the function just once, which is especially important when filtering large arrays.

Comment (luckyjsx) [reply app/views/RoomMembersView/index.tsx]: @OtavioStasiak I made the requested changes

**Review by OtavioStasiak — APPROVED** [review]
Looks good to me!
Nice job!!
