### PR TITLE
[FIX] Change force logout rule

### LINKED ISSUE #1487: RN apps log users out and forget servers intermittently
- Your Rocket.Chat Experimental app version: Official 4.1.0.2095, Experimental 4.2.0
- Your Rocket.Chat server version: 3.0.0 and 2.3.0
- Device (or Simulator) you're running with: Samsung Galaxy JS, HomTom HT72, Android 6.0.1 and Android 7.

Once in a while when I try to open an app or click on a push message, the app launches but prompts me to type in the server address and log in, although I did not log out previously. Difficult to reproduce as it seems to happen without any rule. 
Sometimes it loads the server and channels before logging me out again.

### PR DESCRIPTION
**Pull request by diegolmello**
@RocketChat/ReactNative

Closes #1487

### CODE REVIEW

File: app/sagas/login.js [hunk 1]
```diff
@@ -36,11 +36,11 @@ const handleLoginRequest = function* handleLoginRequest({ credentials, logoutOnE
 			result = yield call(loginWithPasswordCall, credentials);
 		}
 		return yield put(loginSuccess(result));
-	} catch (error) {
-		if (logoutOnError) {
+	} catch (e) {
+		if (logoutOnError && (e.data && e.data.message && /you've been logged out by the server/i.test(e.data.message))) {
```
Comment (ggazzo) [inline app/sagas/login.js]: 👍
