### PR TITLE
[BUG] Profile screen gets frozen when submitting invalid current password

### LINKED ISSUE #968: [BUG] Profile screen gets frozen when submitting invalid current password
Steps to reproduce:
1. Go to Profile screen
2. Type new password in New Password field
3. Click Submit
4. In prompt that requires old password type invalid old password
5. Click Ok
6. Alert "There was an error while profile update" appears

Actual Result: screen gets frozen (no response for any gesture).
Expected Result: profile form can be submitted again.

ezgif com-video-to-gif (4)

- Your Rocket.Chat Experimental app version: 1.14.0.8337
- Your Rocket.Chat server version: open.rocket.chat
- Device (or Simulator) you're running with Iphone SE 12.1.4

### PR DESCRIPTION
**Pull request by IlarionHalushka**
@RocketChat/ReactNative
Closes #968 

Screen froze because of [react-native issue](https://github.com/facebook/react-native/issues/10471) which appears when Alert is being triggered while Modal hiding is kind of in progress.

So a temporary work-around for this RN issue is to hide `Enter Current Password`  on Alert `OK` press

### CODE REVIEW

File: app/utils/info.js [hunk 1]
```diff
@@ -29,4 +29,5 @@ export const Toast = React.forwardRef((props, ref) => (
 		opacity={0.8}
 	/>
 ));
-export const showErrorAlert = (message: string, title: string) => Alert.alert(title, message, [{ text: 'OK', onPress: () => {} }], { cancelable: true });
+
```
Comment (diegolmello) [inline app/utils/info.js]: Unnecessary

File: yarn.lock [hunk 2]
```diff
@@ -1230,9 +1230,9 @@
   integrity sha1-p3c2C1s5oaLlEG+OhY8v0tBgxXA=
 
 "@react-native-community/cli@^1.2.1":
-  version "1.9.4"
-  resolved "https://registry.yarnpkg.com/@react-native-community/cli/-/cli-1.9.4.tgz#51e4ba30aa6ee29f0c1e2bedf69ac7d1a4df1a8c"
-  integrity sha512-7XjgqCdi23g6V7RV4tsYvqVqOBtNjAsWe5Oj2dR5KxDi3YqUyIyPjDWzyFkIxiO9XTGp9Al4QSmRwtOERvHO8A==
+  version "1.9.8"
```
Comment (diegolmello) [inline yarn.lock]: Unnecessary
