### PR TITLE
[FIX] Logout from custom oauth

### LINKED ISSUE #1818: Logout from custom oauth does not log user out
- Your Rocket.Chat Experimental app version: 4.4.0
- Your Rocket.Chat server version: 3.0.0
- Device (or Simulator) you're running with: Android (9) and IOS (11.4)

When authenticated through custom oauth, logging out from the server does not completely log user out. 

Steps to reproduce:
- Authenticate through custom oauth
- Logout
- Log back in --> app redirects back in to the previous signed in account without user having to enter a new credentials.

### PR DESCRIPTION
**Pull request by EzequielDeOliveira**
This PR allow the user choose if want to clear cookies from OAuth webview.
Fix #1818 

##### Using my github account to login, I was asked if I want to clear cookies. if I click "Ok", the cookies will be cleared, but if I cancel just one logout happens.
ezgif com-video-to-gif(32)

##### Using my account with email and password the question about cookies doesn't appear.
ezgif com-video-to-gif(33)

### CODE REVIEW

File: app/sagas/login.js [hunk 1]
```diff
@@ -40,6 +40,7 @@ const handleLoginRequest = function* handleLoginRequest({ credentials, logoutOnE
 			result = yield call(loginCall, credentials);
 		} else {
 			result = yield call(loginWithPasswordCall, credentials);
+			result.loginEmailPassword = credentials.loginEmailPassword;
```
Comment (diegolmello) [inline app/sagas/login.js:43]: This could be done inside `loginWithPasswordCall`

File: app/sagas/login.js [hunk 2]
```diff
@@ -133,7 +136,7 @@ const handleLoginSuccess = function* handleLoginSuccess({ user }) {
 
 		yield RNUserDefaults.set(`${ RocketChat.TOKEN_KEY }-${ server }`, user.id);
 		yield RNUserDefaults.set(`${ RocketChat.TOKEN_KEY }-${ user.id }`, user.token);
-		yield put(setUser(user));
+		yield put(setUser({ ...user, loginEmailPassword: u.loginEmailPassword }));
```
Comment (diegolmello) [inline app/sagas/login.js:139]: IMO we shouldn't keep this value on Redux, which will make these changes unnecessary

File: app/views/LoginView.js [hunk 3]
```diff
@@ -118,8 +118,9 @@ class LoginView extends React.Component {
 
 		const { user, password } = this.state;
 		const { loginRequest } = this.props;
+		const loginEmailPassword = true;
 		Keyboard.dismiss();
-		loginRequest({ user, password });
+		loginRequest({ user, password, loginEmailPassword });
```
Comment (diegolmello) [inline app/views/LoginView.js:123]: If you pass these info inside `loginWithPasswordCall`, these changes won't be necessary.

File: app/views/SettingsView/index.js [hunk 4]
```diff
@@ -87,15 +89,33 @@ class SettingsView extends React.Component {
 		return roles?.includes('livechat-agent');
 	}
 
+	logout = () => {
+		const { logout, user } = this.props;
+		if (!user.loginEmailPassword) {
```
Comment (diegolmello) [inline app/views/SettingsView/index.js:94]: Following my comments, this would be a user query instead of Redux.
It's going to make the code on this call slightly complex, but will simplify the rest of the code a lot.

File: app/views/SettingsView/index.js [hunk 5]
```diff
@@ -87,15 +89,33 @@ class SettingsView extends React.Component {
...
+			showConfirmationAlert({
+				title: 'Clear all cookies from login OAuth?',
```
Comment (diegolmello) [inline app/views/SettingsView/index.js:96]: i18n missing
