### PR TITLE
fix: Profile formIsChanged logic

### LINKED ISSUE #6166: bug: update profile data will display incorrect message
**Description**
When updating user profile data like name or email, even if the data is invalid (like empty) it will still show "Profile saved successfully" alert.
[Video](https://github.com/user-attachments/assets/265fcd5a-f04c-4fbb-b5c4-e1097e209884)

**Steps to Reproduce**
1. Open profile page
2. Update one of the required field to empty (name / email)
3. App will show "Profile saved successfully" message
4. Move to other page
5. Reopen Profile page (field will still be populated with no change)

**Expected Behavior**
- Alert Message should show error like "name cannot be empty"

**Actual Behavior**
- Alert message will keep showing  "Profile saved successfully" 

Device : iPhone 13 Pro (iOS 18.3.1) 
App Version : 4.57.2.73496

### PR DESCRIPTION
**Pull request by anirbanpaulcom**
## Issue(s)	

Closes #6166 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by diegolmello — CHANGES_REQUESTED** [review]
Your PR fixes an issue, but it should be using `react-hook-form` https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/aa3938a2a46a3694f874350c6aaf73062a114e3c/app/views/CreateChannelView/index.tsx#L86

Can you migrate this component?

**Comment by anirbanpaulcom** [comment]
> Your PR fixes an issue, but it should be using `react-hook-form`
> 
> https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/aa3938a2a46a3694f874350c6aaf73062a114e3c/app/views/CreateChannelView/index.tsx#L86
> 
> Can you migrate this component?

 @diegolmello Can you please tell me how to migrate it because the React Hook 'useForm' cannot be called in a class component, or should I wrap it?

**Comment by anirbanpaulcom** [comment]
> Your PR fixes an issue, but it should be using `react-hook-form`
> 
> https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/aa3938a2a46a3694f874350c6aaf73062a114e3c/app/views/CreateChannelView/index.tsx#L86
> 
> Can you migrate this component?

@diegolmello  Can you please tell me how to migrate it because the React Hook 'useForm' cannot be called in a class component, or should I wrap it?

**Comment by diegolmello** [comment]
Hey @anirbanpaulcom.
Can you migrate the component to hooks on another PR and then use react-hook-form?
Thanks!

**Comment by anirbanpaulcom** [comment]
> Hey @anirbanpaulcom.
> Can you migrate the component to hooks on another PR and then use react-hook-form?
> Thanks!

@diegolmello , Please take a look, PR : #5646

File: app/views/ProfileView/index.tsx [hunk 1]
```diff
@@ -155,15 +155,15 @@ class ProfileView extends React.Component<IProfileViewProps, IProfileViewState>
...
+			(!newPassword?.trim() || !newPassword) &&
+			(!email || !email.trim() || (user.emails && user.emails[0].address === email)) &&
 			user.bio === bio &&
 			user.nickname === nickname &&
-			!newPassword &&
-			user.emails &&
-			user.emails[0].address === email &&
 			!customFieldsChanged
 		);
+
```
Comment (diegolmello) [inline app/views/ProfileView/index.tsx:166]:
```suggestion
```

**Review by diegolmello — APPROVED** [review]
