### PR TITLE
[FIX] Don't show Block Button inside Group DM Actions

### LINKED ISSUE #3111: In group personal correspondence there is a button "Block user" and it does not work
### Description:

In group personal correspondence there is a button "Block user" and it does not work. I suppose that in group personal correspondence this button should not be, it should only be in personal correspondence with one user. 
And in group personal correspondence instead of it there should be a button "Leave channel", which is in all other group types of chats.

### Environment Information:

- Rocket.Chat Server Version: 3.13.2
- Rocket.Chat App Version: 4.16.1.23838
- Device Name: Iphone 11 pro max
- OS Version: ios 14.4.2

### Steps to reproduce:

1. create a group personal correspondence with several users
2. go to the channel information screen
3. click "Block user" button
4. Nothing happens

### Expected behavior:

3. there is no button "Block user", there is a button  "Leave channel"

### Actual behavior:

3. there is a button "Block user" and it does not work

### PR DESCRIPTION
**Pull request by reinaldonetof**
## Proposed changes

That don't show the `Block user` button inside the Group DM's actions

## Issue(s)	

https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3111

## How to test or reproduce

- Create a Group DM
- Go to Group DM's actions

## Screenshots

<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>

</td>
<td>

</td>
</tr>
</tbody>
</table>

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

Closes #3111

### CODE REVIEW

File: app/views/RoomActionsView/index.js [hunk 1]
```diff
@@ -713,13 +713,13 @@ class RoomActionsView extends React.Component {
...
 		const { theme } = this.props;
-		const { t, blocker } = room;
+		const { t, blocker, usernames } = room;
 
 		if (!joined || t === 'l') {
 			return null;
 		}
 
-		if (t === 'd') {
+		if (t === 'd' && usernames.length === 2) {
```
Comment (diegolmello) [inline app/views/RoomActionsView/index.js:722]: Let's use `RocketChat.isGroupChat`

**Review by diegolmello — CHANGES_REQUESTED** [review]
