### PR TITLE
[FIX] Logout from other locations not prompting confirmation option

### LINKED ISSUE #2847: [Bug] iOS has no 'OK' button when logged out from other locations (devices)
### Description:

[Bug] iOS has no 'OK' button when logged out from other locations (devices)

### Environment Information:

- Rocket.Chat Server Version: 3.7.1
- Rocket.Chat App Version: 4.14.0.22701
- Device Name: iPhone 12
- OS Version: iOS 14.4 

### Steps to reproduce:

1. User tried to "logged out from other locations" on mobile application (iOS) 
2. Pop Up 'Are you sure?' has shown but has only 'Cancel' button (according to the screenshot) while the pop up on android has shown both 'OK' & 'Cancel' button

### Expected behavior:

Pop up on iOS application appears both 'OK' & 'Cancel' button like android

### Actual behavior:

Nothing happens.
S__58982418

### Additional context:

Working !!

### PR DESCRIPTION
**Pull request by ARKEOLOGIST**
## Proposed changes
Should fix #2847 when deployed. The logout toast is now passed a 'confirmationText' prop to allow it to render the 'OK' button correctly on both Android and iOS (bugs occurs in iOS).

## Issue(s)	
Should close #2847.

## How to test or reproduce
Trying to logout from the profile page would not render the 'OK' button on iOS.

## Screenshots

<Would definitely appreciate someone helping me a bit with this, will update accordingly> 

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [X] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/views/ProfileView/index.js [hunk 1]
```diff
@@ -436,6 +436,7 @@ class ProfileView extends React.Component {
 		logEvent(events.PROFILE_LOGOUT_OTHER_LOCATIONS);
 		showConfirmationAlert({
 			message: I18n.t('You_will_be_logged_out_from_other_locations'),
+			confirmationText: I18n.t('OK'),
 			callToAction: I18n.t('Logout'),
```
Comment (diegolmello) [inline app/views/ProfileView/index.js:440]: There was a PR merged right after `Logout from other locations feature` which refactored `showConfirmationAlert` renaming `callToAction` to `confirmationText`.

This might work without other changes:
```suggestion
			confirmationText: I18n.t('Logout'),
```

**Review by diegolmello — CHANGES_REQUESTED** [review]

File: app/views/ProfileView/index.js (hunk 1 above)
Comment (ARKEOLOGIST) [reply app/views/ProfileView/index.js:440]: Should I just close my PR then? I think that PR should solve the issue. I can send in another PR if the issue keeps occurring.

Comment (ARKEOLOGIST) [reply app/views/ProfileView/index.js:440]: I'll fix this.

Comment (ARKEOLOGIST) [reply app/views/ProfileView/index.js]: @diegolmello Do have a look when you're free. I've resolved it!

**Review by diegolmello — APPROVED** [review]
LGTM
