### PR TITLE
[FIX] Wrong styling on E2E encryption banner

### LINKED ISSUE #2629: Wrong styling on E2E banner
### Environment Information:

- Rocket.Chat Server Version: any
- Rocket.Chat App Version: 4.12
- Device Name: any
- OS Version: any

### Steps to reproduce:

1. Have e2e banner displaying (just login)

### Expected behavior:

Banner's style should follow `Sorting` alignment.
Screen Shot 2020-11-11 at 10 44 49

### Actual behavior:

It's misaligned.
Screen Shot 2020-11-11 at 10 45 17

### PR DESCRIPTION
**Pull request by gerzonc**
## Proposed changes
Instead of using the ```Banner``` component as I previously proposed, using just the List.Item component was more than enough to solve this issue. Thanks to @diegolmello for the idea.

## Issue(s)	

Closes #2629

## Screenshots

Before
image

After

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/containers/List/ListItem.js [hunk 1]
```diff
@@ -86,7 +86,7 @@ const Button = React.memo(({
 }) => (
 	<Touch
 		onPress={() => onPress(props.title)}
-		style={{ backgroundColor: themes[props.theme].backgroundColor }}
+		style={{ backgroundColor: props.backgroundColor || themes[props.theme].backgroundColor }}
```
Comment (diegolmello) [inline app/containers/List/ListItem.js:89]: Name the prop on params just like `onPress`, so we can use `backgroundColor` instead of `props.backgroundColor`.

File: app/views/RoomsListView/ListHeader/index.js [hunk 2]
```diff
@@ -1,28 +1,80 @@
 import React from 'react';
 import PropTypes from 'prop-types';
 
-import Sort from './Sort';
-import Encryption from './Encryption';
+import { withTheme } from '../../../theme';
+import I18n from '../../../i18n';
+import { Item } from '../../../containers/List';
```
Comment (diegolmello) [inline app/views/RoomsListView/ListHeader/index.js:6]: Check how this import is done for `List` on other places of the app.
The idea here is to always call `List.Item`, so we follow the same pattern.

File: app/views/RoomsListView/ListHeader/index.js [hunk 3]
```diff
@@ -1,28 +1,80 @@
...
+							<CustomIcon
+								name='encrypted'
+								color={themes[theme].buttonText}
+								size={22}
+							/>
+						)}
+						backgroundColor={themes[theme].actionTintColor}
+						color={themes[theme].buttonText}
+						onPress={goEncryption}
+						translateTitle
```
Comment (diegolmello) [inline app/views/RoomsListView/ListHeader/index.js:49]: It's default true. You can remove it.

**Review by diegolmello — CHANGES_REQUESTED** [review]
Almost there!
Left a few comments.
Can you add screenshots of before and after your PR?

File: app/containers/List/ListItem.js [hunk 4]
```diff
@@ -46,47 +43,68 @@ const styles = StyleSheet.create({
...
-));
+			) : null}
+		</View>
+	)
+);
 
-const Button = React.memo(({
-	onPress, ...props
-}) => (
+const Button = React.memo(({ onPress, backgroundColor, ...props }) => (
```
Comment (diegolmello) [inline app/containers/List/ListItem.js:102]: Since you're adding a background color, you should also add the option to overwrite `underlayColor` from `Touch`.
Sending it as a prop should work as `Touch` has `{...props}`, but be aware not to change the behaviour when the prop isn't sent.

After this, add the new colors to `colors.js` (We're going to refactor it as soon as we get themes on web client).
I suggest the name `tintActive`.
Light: `#549DF9`
Dark: `#549DF9`
Black: `#76B7FC`

It should behave like this:
Jan-12-2021 18-53-12

**Review by diegolmello — CHANGES_REQUESTED** [review]

File: app/containers/List/ListItem.js (hunk 4 above)
Comment (diegolmello) [reply app/containers/List/ListItem.js:102]: Don't forget to add stories for the new props.

File: app/containers/List/ListItem.js [hunk 5]
```diff
@@ -46,47 +43,71 @@ const styles = StyleSheet.create({
...
-		<View style={styles.textContainer}>
-			<Text style={[styles.title, { color: color || themes[theme].titleText }]} numberOfLines={1}>{translateTitle ? I18n.t(title) : title}</Text>
-			{subtitle
-				? <Text style={[styles.subtitle, { color: themes[theme].auxiliaryText }]} numberOfLines={1}>{translateSubtitle ? I18n.t(subtitle) : subtitle}</Text>
-				: null
-			}
-		</View>
-		{right || showActionIndicator
-			? (
+const Content = React.memo(
```
Comment (diegolmello) [inline app/containers/List/ListItem.js:50]: You didn't add any logic here.
Why did you change it?

File: app/containers/List/ListItem.js [hunk 6]
```diff
@@ -99,15 +120,21 @@ const ListItem = React.memo(({ ...props }) => {
 		return <Button {...props} />;
 	}
 	return (
-		<View style={{ backgroundColor: themes[props.theme].backgroundColor }}>
+		<View
+			style={{
+				backgroundColor:
+          props.backgroundColor || themes[props.theme].backgroundColor
```
Comment (diegolmello) [inline app/containers/List/ListItem.js:126]: Can you destructure `backgroundColor` just to follow the same pattern as Button?

File: app/views/RoomsListView/ListHeader/index.js [hunk 7]
```diff
@@ -1,28 +1,80 @@
...
-	encryptionBanner,
-	user
-}) => (
-	<>
-		<Encryption searching={searching} goEncryption={goEncryption} encryptionBanner={encryptionBanner} />
-		<Sort searching={searching} sortBy={sortBy} toggleSort={toggleSort} />
-		<OmnichannelStatus searching={searching} goQueue={goQueue} inquiryEnabled={inquiryEnabled} queueSize={queueSize} user={user} />
-	</>
-));
+const ListHeader = React.memo(
```
Comment (diegolmello) [inline app/views/RoomsListView/ListHeader/index.js:13]: Same as the other component.
Review your IDE and change only affected lines, please.

File: storybook/stories/List.js [hunk 8]
```diff
@@ -119,6 +119,22 @@ stories.add('with custom color', () => (
...
+));
+
+stories.add('with background and underlay color', () => (
+	<List.Container>
+		<List.Separator />
+		<List.Item title='Some title for banner' color='white' onPress={() => alert('Hi there!')} backgroundColor='red' underlayColor='darkred' translateTitle={false} />
+		<List.Separator />
+	</List.Container>
+));
+
```
Comment (diegolmello) [inline storybook/stories/List.js:137]: Add them to `with custom colors` story

**Review by diegolmello — CHANGES_REQUESTED** [review]

**Review by diegolmello — APPROVED** [review]
