### PR TITLE
[FIX] Read receipts on tablet

### LINKED ISSUE #2295: Read Receipts don't open in new Action Sheet on tablet
- Your Rocket.Chat Experimental app version: 4.9.0.308
- Your Rocket.Chat server version: 3.4.2
- Device (or Simulator) you're running with: iPad iOS 13.6

When trying to open the read receipts on iPad, they don't open, the action sheet just closes.

The same app version on iPhone works.

IScreenshot of action sheet

### PR DESCRIPTION
**Pull request by phriedrich**
@RocketChat/ReactNative

Closes #2295

### CODE REVIEW

**Comment by phriedrich** [comment]
@djorkaeffalexandre Thank you! That worked and it displays the close button now.

File: app/views/ReadReceiptView/index.js [hunk 1]
```diff
@@ -17,8 +18,14 @@ import { getUserSelector } from '../../selectors/login';
...
 
 class ReadReceiptView extends React.Component {
-	static navigationOptions = {
-		title: I18n.t('Read_Receipt')
+	static navigationOptions = ({ navigation, isMasterDetail }) => {
+		const options = {
+			title: I18n.t('Read_Receipt')
+		};
+		if (isMasterDetail) {
+			options.headerLeft = () => <CloseModalButton navigation={navigation} testID='readreceipt-view-close' />;
```
Comment (djorkaeffalexandre) [inline app/views/ReadReceiptView/index.js:26]:
```suggestion
			options.headerLeft = () => <CloseModalButton navigation={navigation} testID='read-receipt-view-close' />;
```

**Comment by diegolmello** [comment]
@phriedrich Thanks for your contribution! :)
