### PR TITLE
fix: custom status text wrap in drawer

### LINKED ISSUE #6776: bug: custom status text wraps onto multiple lines in the sidebar
### Describe the Bug

The custom status text in the user drawer is displayed on multiple lines instead of being truncated or limited to a single line.

### Steps to Reproduce

1. Open the sidebar.
2. Set a long custom status message.
3. Save the status and return to the main view.
4. Open the sidebar again.
5. Observe that the custom status text wraps onto multiple lines instead of remaining on a single line.

### Expected Behavior

The custom status text should be displayed on a single line, truncated with an ellipsis (...) if it exceeds the available width

### Actual Behavior

The custom status text wraps to multiple lines

Image

### Rocket.Chat Server Version

7.13.0

### Rocket.Chat App Version

4.66.0

### Device Name

All Devices

### OS Version

All OS

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Yaddalapalli-Charan-Kumar-Naidu**
## Proposed changes
This PR fixes a UI issue where the **Custom Status text** in the sidebar would overflow or wrap into multiple lines, causing layout misalignment.  

The fix ensures that the status message is **truncated with ellipsis (`...`)** when it exceeds a single line, maintaining a clean and consistent sidebar layout across all devices and themes.

## Issue(s)	
Closes #6776 
https://rocketchat.atlassian.net/browse/COMM-95

## How to test or reproduce
1. Open the **sidebar** where the user's **Custom Status** appears.
2. Set a long custom status, for example:
3. Verify that:
- The status text now appears on **only one line**.
- Long text is truncated with `...` at the end.
- Sidebar layout remains aligned and visually consistent.

## Screenshots
| Before | After |
|--------|-------|
|  |  |

Screenshot 2025-12-10 at 2 21 36 PM

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Summary by CodeRabbit

* **Bug Fixes**
  * Long list item titles now reliably truncate to preserve layout.

* **New Features**
  * Title rendering accepts a configurable line limit (numberOfLines) for truncation.
  * Sidebar status titles default to a single-line display for consistent layout.

* **Documentation / Demo**
  * Story/demo updated to showcase long-title truncation and layout behavior.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by Yaddalapalli-Charan-Kumar-Naidu** [comment]
@Rohit3523 @diegolmello can you review my PR and let me any further modifications needed in this

**Comment by Yaddalapalli-Charan-Kumar-Naidu** [comment]
Hey @Rohit3523 , one of the tests failed in the CI run. Could you please help me check what might be causing it?

**Comment by Rohit3523** [comment]
> Hey @Rohit3523 , one of the tests failed in the CI run. Could you please help me check what might be causing it?

Update the storybook snap using `yarn test-update` and make sure you are using node 22

**Comment by Yaddalapalli-Charan-Kumar-Naidu** [comment]
> > Hey @Rohit3523 , one of the tests failed in the CI run. Could you please help me check what might be causing it?
> 
> Update the storybook snap using `yarn test-update` and make sure you are using node 22

ok, I will check and update it

**Comment by Yaddalapalli-Charan-Kumar-Naidu** [comment]
@Rohit3523 @diegolmello can anyone review the PR and let me know any changes required

**Comment by Rohit3523** [comment]
I think it will also truncate other list items, can you please test this case

**Comment by Yaddalapalli-Charan-Kumar-Naidu** [comment]
@Rohit3523 made changes such that it only truncates particular status list item

File: app/containers/List/ListItem.tsx [hunk 1]
```diff
@@ -62,16 +62,20 @@ const styles = StyleSheet.create({
...
 	'use memo';
 
 	const { colors } = useTheme();
 	switch (typeof title) {
 		case 'string':
 			return (
-				<Text style={[styles.title, styleTitle, { color: color || colors.fontDefault }]}>
+				<Text
+					numberOfLines={numberOfLines}
+					ellipsizeMode={ellipsizeMode as any}
```
Comment (Rohit3523) [inline app/containers/List/ListItem.tsx]: Not a good idea to use any type here

Comment (Yaddalapalli-Charan-Kumar-Naidu) [reply app/containers/List/ListItem.tsx]: ok sure, I have updated it

**Comment by Rohit3523** [comment]
Can you please update your branch with develop and add a before screenshot in the PR description
Leave a comment once done

**Comment by Yaddalapalli-Charan-Kumar-Naidu** [comment]
@Rohit3523 I have updated the develop branch and also added a screenshot for before in the PR description

**Comment by Yaddalapalli-Charan-Kumar-Naidu** [comment]
@Rohit3523 @diegolmello @OtavioStasiak can anyone review my PR

**Comment by Rohit3523** [comment]
Hey, sorry for the delay.

In `app/containers/List/List.stories.tsx`, can you please add one more List component in `TitleAndSubtitle` function and pass `numberOfLines={1}` and `ellipsizeMode` in the prop. You can also use the same code from line 22 and add numberOfLines and remove others

**Comment by Rohit3523** [comment]
You can remove the other props and keep text and new prop you have added, also after this run `yarn test-update` to update the snapshot

**Comment by Yaddalapalli-Charan-Kumar-Naidu** [comment]
ok sure

**Comment by Rohit3523** [comment]
Sorry, I just noticed it is important to have translateTitle={false} because title will translate if we don't pass this props ;-;

**Comment by Yaddalapalli-Charan-Kumar-Naidu** [comment]
ok I will update it

**Comment by Rohit3523** [comment]
Umm, ellipsizeMode is missing ;-;

**Comment by Yaddalapalli-Charan-Kumar-Naidu** [comment]
added the the ellipsizeMode prop

**Comment by Rohit3523** [comment]
Looking good to merge

**Comment by Yaddalapalli-Charan-Kumar-Naidu** [comment]
Thanks a lot for the review and your support

**Comment by Yaddalapalli-Charan-Kumar-Naidu** [comment]
can you approve this PR and merge it

File: app/views/SidebarView/components/CustomStatus.tsx [hunk 2]
```diff
@@ -72,6 +72,8 @@ const CustomStatus = () => {
 				onPress={() => (presenceBroadcastDisabled ? onPressPresenceLearnMore() : sidebarNavigate('StatusView'))}
 				translateTitle={!statusText}
 				testID={`sidebar-custom-status-${status}`}
+				numberOfLines={1}
+				ellipsizeMode='tail'
```
Comment (diegolmello) [inline app/views/SidebarView/components/CustomStatus.tsx]: Text's default `ellipsizeMode` is `tail` already, so we don't have to add a prop for that https://reactnative.dev/docs/text#ellipsizemode

Comment (Yaddalapalli-Charan-Kumar-Naidu) [reply app/views/SidebarView/components/CustomStatus.tsx]: ok sure, I have read the documentation and updated it

Comment (Yaddalapalli-Charan-Kumar-Naidu) [reply app/views/SidebarView/components/CustomStatus.tsx]: @diegolmello I have made changes as per you request

**Review by diegolmello — APPROVED** [review]

**Comment by diegolmello** [comment]
@Yaddalapalli-Charan-Kumar-Naidu merged, thanks for your contribution!

**Comment by Yaddalapalli-Charan-Kumar-Naidu** [comment]
@diegolmello Thank you, I appreciate the review and guidance. Excited to continue contributing
