### PR TITLE
[FIX] Remove the tmid parameter when it is empty

### LINKED ISSUE #4491: Slash commands do not work with server version 5.1.0
### Description:

Hello Devs.

After upgrading the Server to 5.1.0 slash commands do not work anymore. No /shrug, no /poll, no /remind. Did not test more slash commands. It's odd because I have configured to servers and the one running 4.8.3 runs slash commands just fine.

### Environment Information:

- Rocket.Chat Server Version: 5.1.0
- Rocket.Chat App Version: 4.30.0
- Device Name: Pixel 6
- OS Version: Android 12

### Steps to reproduce:

1. Go to a channel
2. Type /shrug
3. Nothing happens.

### Expected behavior:

ASCII shrug appears.

### Actual behavior:

Nothing happens.

### PR DESCRIPTION
**Pull request by GleidsonDaniel**
## Proposed changes

Remove the tmid parameter when it is empty

Tested on servers:
4.8
5.0
5.2

Closes #4491

## How to test or reproduce

Try to run any slash command

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/lib/services/restApi.ts [hunk 1]
```diff
@@ -681,7 +681,7 @@ export const getSyncThreadsList = ({ rid, updatedSince }: { rid: string; updated
 		updatedSince
 	});
 
-export const runSlashCommand = (command: string, roomId: string, params: string, triggerId?: string, tmid?: string) =>
+export const runSlashCommand = (command: string, roomId: string, params: string, triggerId?: string, tmid?: string | null) =>
 	// RC 0.60.2
 	sdk.post('commands.run', {
```
Comment (reinaldonetof) [inline app/lib/services/restApi.ts:686]: IMHO, I think the best approach is change `tmid` @691 to `...(tmid && { tmid })`, also we can remove the `null`

**Review by reinaldonetof — CHANGES_REQUESTED** [review]

**Review by diegolmello — APPROVED** [review]
