### PR TITLE
fix(Android): Remove RefreshControl from messages list

### LINKED ISSUE #5261: IndexOutOfBoundsException immediately after submitting message
### Description:

Under certain circumstances, the Android app crashes immediately after submitting a message.

### Environment Information:

- Rocket.Chat Server Version: 6.4.0
- Rocket.Chat App Version: 4.41.0.49563
- Device Name: ELE-L29 (Huawei P30)
- OS Version: EMUI 12.0.0 (Android 11)

### Steps to reproduce:

Unfortunately, I don't know the preconditions for the problem to occur. However, in case it is occur to submit a single message to observe an app crash.

I will add further informations to this bug report in case I'm able to determine the preconditions for this problem to occur.

### Expected behavior:

The app does not crash.

### Actual behavior:

The app crashes. An `IndexOutOfBoundsException` can be found in the device log.

### Additional context:

The stack trace of the exception:

```
10-08 12:38:25.887  8724  8724 E AndroidRuntime: FATAL EXCEPTION: main
10-08 12:38:25.887  8724  8724 E AndroidRuntime: Process: chat.rocket.android, PID: 8724
10-08 12:38:25.887  8724  8724 E AndroidRuntime: java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 2 (child count is 2)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.getAndVerifyPreorderedIndex(ViewGroup.java:2194)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4383)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.draw(View.java:22002)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20859)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20817)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:583)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:589)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4317)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4125)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3385)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:911)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:900)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8668)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
10-08 12:38:25.887  8724  8724 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

### PR DESCRIPTION
**Pull request by diegolmello**
## Proposed changes

We caught `getChildDrawingOrder() returned invalid index 2 (child count is 2)` on Bugsnag happening on Android with these steps:
- Scroll until FAB appears
- Focus on composer
- Tap FAB
- App crashes

It's more noticeable on Android 13 and it's very likely to be a regression after https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5207

The root cause seems to be related to RefreshControl:
- https://github.com/synonymdev/bitkit/issues/1109
- https://github.com/software-mansion/react-native-reanimated/issues/4306

After testing older version of the app, we found that RefreshControl was not working properly on Android and we got no feedback about this bug. That's probably because it's not really a common feature to be expected from a chat app, hence low usage.
Since the cost to maintain such an edge case feature is too high (), we're removing it from Android. We can reevaluate iOS counterpart later and plan a full removal, if needed.

More on ScrollView/RefreshControl:
- https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3260
- https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4536

## Issue(s)	

closes #5261 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

[NATIVE-409]

[NATIVE-409]: https://rocketchat.atlassian.net/browse/NATIVE-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: app/views/RoomView/index.tsx [hunk 1]
```diff
@@ -1361,8 +1361,8 @@ class RoomView extends React.Component<IRoomViewProps, IRoomViewState> {
 		if (showUnreadSeparator || dateSeparator) {
 			return (
 				<>
-					<Separator ts={dateSeparator} unread={showUnreadSeparator} />
 					{content}
+					<Separator ts={dateSeparator} unread={showUnreadSeparator} />
```
Comment (diegolmello) [inline app/views/RoomView/index.tsx:1365]: This is needed in order to show the separator on the right place.
Since we're not using the same inverting list technique anymore, we need to reposition.

File: app/views/RoomView/List/components/index.ts [hunk 2]
```diff
@@ -1,4 +1,3 @@
 export * from './NavBottomFAB';
-export * from './RefreshControl';
```
Comment (GleidsonDaniel) [inline app/views/RoomView/List/components/index.ts:2]: I think we can keep the component, just remove the implementation, who knows, maybe in the future we will reuse it and reimplement this functionality.

**Review by GleidsonDaniel — APPROVED** [review]
