### PR TITLE
[FIX] App not prompting join code for password protected channels

### LINKED ISSUE #2258: App does not prompt user to enter password for password protected channels
- Your Rocket.Chat Experimental app version: 4.6.4
- Your Rocket.Chat server version: 3.1.1
- Device (or Simulator) you're running with: iPhone 11 (iOS 13.5 - Simulator)

App does not prompt user for password when joining password-protected channels. User is unable to join the room with the following response (/api/v1/channels.join):

`{
	"success": false,
	"error": "Invalid Room Password [error-code-invalid]",
	"errorType": "error-code-invalid",
	"details": {
		"method": "joinRoom"
	}
}`

Simulator Screen Shot - iPhone 11 - 2020-07-08 at 13 22 23

### PR DESCRIPTION
**Pull request by DanMke**
Co-authored-by: Vitor Leal <vitor_leal2201@hotmail.com>
Co-authored-by: Fernando Aguilar <fernando.aguilar@hotmail.com.br>

## Proposed changes

Creating an input for password insertion when the channel is password protected, and creating a status in RoomView to store the joinCode attribute described in the documentation (https://docs.rocket.chat/api/rest-api/methods/channels/join) to send in the post when the channel is password protected.

## Issue(s)	

Closes #2258 

## How to test or reproduce

To reproduce, just try to enter a password-protected channel, no field will appear to enter the password, and it will not be possible to enter.

## Screenshots

Screen Shot 2020-10-13 at 1 57 13 PM
Screen Shot 2020-10-13 at 1 57 18 PM
Screen Shot 2020-10-13 at 2 11 09 PM

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/lib/methods/subscriptions/rooms.js [hunk 1]
```diff
@@ -32,7 +32,7 @@ const createOrUpdateSubscription = async(subscription, room) => {
 		const db = database.active;
 		const subCollection = db.collections.get('subscriptions');
 		const roomsCollection = db.collections.get('rooms');
-
+		subscription.joinCodeRequired = room.joinCodeRequired;
```
Comment (djorkaeffalexandre) [inline app/lib/methods/subscriptions/rooms.js:35]: Wrong place, this should be done on `mergeSubscriptionsRooms`

File: app/lib/methods/helpers/findSubscriptionsRooms.js [hunk 2]
```diff
@@ -49,7 +49,8 @@ export default async(subscriptions = [], rooms = []) => {
 			departmentId: s.departmentId,
 			servedBy: s.servedBy,
 			livechatData: s.livechatData,
-			tags: s.tags
+			tags: s.tags,
+			joinCode: s.joinCode
```
Comment (djorkaeffalexandre) [inline app/lib/methods/helpers/findSubscriptionsRooms.js:53]: `joinCode` -> `joinCodeRequired`

File: app/lib/methods/subscriptions/rooms.js [hunk 3]
```diff
@@ -79,7 +79,8 @@ const createOrUpdateSubscription = async(subscription, room) => {
 					departmentId: s.departmentId,
 					servedBy: s.servedBy,
 					livechatData: s.livechatData,
-					tags: s.tags
+					tags: s.tags,
+					joinCode: s.joinCode
```
Comment (djorkaeffalexandre) [inline app/lib/methods/subscriptions/rooms.js:83]: `joinCode` -> `joinCodeRequired`

Comment (djorkaeffalexandre) [inline app/lib/methods/subscriptions/rooms.js:83]: Add this to room too, line 113.

Comment (djorkaeffalexandre) [inline app/lib/methods/subscriptions/rooms.js:83]: Add this to `findSubscriptionsRooms` too

File: app/lib/database/schema/app.js [hunk 4]
```diff
@@ -49,7 +49,8 @@ export default appSchema({
 				{ name: 'department_id', type: 'string', isOptional: true },
 				{ name: 'served_by', type: 'string', isOptional: true },
 				{ name: 'livechat_data', type: 'string', isOptional: true },
-				{ name: 'tags', type: 'string', isOptional: true }
+				{ name: 'tags', type: 'string', isOptional: true },
+				{ name: 'join_code', type: 'string', isOptional: false }
```
Comment (djorkaeffalexandre) [inline app/lib/database/schema/app.js:53]: `join_code` -> `join_code_required`
`string` -> `boolean`

File: app/lib/database/model/migrations.js [hunk 5]
```diff
@@ -129,6 +129,17 @@ export default schemaMigrations({
...
 				})
 			]
+		},
+		{
+			toVersion: 10,
+			steps: [
+				addColumns({
+					table: 'subscriptions',
+					columns: [
+						{ name: 'join_code', type: 'string', isOptional: false }
```
Comment (djorkaeffalexandre) [inline app/lib/database/model/migrations.js:139]: `join_code_required`
`boolean`

File: app/lib/database/model/Subscription.js [hunk 6]
```diff
@@ -109,4 +109,6 @@ export default class Subscription extends Model {
 	@json('livechat_data', sanitizer) livechatData;
 
 	@json('tags', sanitizer) tags;
+
+	@field('join_code') joinCode;
```
Comment (djorkaeffalexandre) [inline app/lib/database/model/Subscription.js:113]: `join_code_required` `joinCodeRequired`

**Review by djorkaeffalexandre — CHANGES_REQUESTED** [review]

**Comment by DanMke** [comment]
The requested fixes have been fixed.
The joinCodeRequired field was added in goRoom.js because when accessing the channel through the directory, this attribute was not passed, it was just being passed when accessing the search bar from outside the directory. This way it is working in both streams.
Conflicts have been fixed.

File: app/utils/goRoom.js [hunk 7]
```diff
@@ -1,13 +1,16 @@
...
-const navigate = ({ item, isMasterDetail, ...props }) => {
+const navigate = async({ item, isMasterDetail, ...props }) => {
 	let navigationMethod = Navigation.navigate;
 
 	if (isMasterDetail) {
 		navigationMethod = Navigation.replace;
 	}
 
+	const { room } = await RocketChat.getRoomInfo(item.rid);
+	item.joinCodeRequired = room.joinCodeRequired;
```
Comment (djorkaeffalexandre) [inline app/utils/goRoom.js:12]: Move to https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/views/DirectoryView/index.js#L152.

File: app/views/RoomView/index.js [hunk 8]
```diff
@@ -56,6 +56,7 @@ import Navigation from '../../lib/Navigation';
 import SafeAreaView from '../../containers/SafeAreaView';
 import { withDimensions } from '../../dimensions';
 import { getHeaderTitlePosition } from '../../containers/Header';
+import TextInput from '../../presentation/TextInput';
```
Comment (djorkaeffalexandre) [inline app/views/RoomView/index.js:59]: Use `containers/TextInput`.

File: app/views/RoomView/styles.js [hunk 9]
```diff
@@ -70,5 +70,11 @@ export default StyleSheet.create({
 	previewMode: {
 		fontSize: 16,
 		...sharedStyles.textMedium
+	},
+	joinInput: {
+		marginTop: 10,
```
Comment (djorkaeffalexandre) [inline app/views/RoomView/styles.js:75]: always use `x4` on all metrics instances.

**Review by djorkaeffalexandre — CHANGES_REQUESTED** [review]

**Comment by DanMke** [comment]
corrections were made, thanks for your attention @djorkaeffalexandre

File: app/lib/database/model/Subscription.js [hunk 10]
```diff
@@ -110,6 +108,8 @@ export default class Subscription extends Model {
 
 	@json('tags', sanitizer) tags;
 
+	@field('join_code_required') joinCodeRequired;
+
```
Comment (djorkaeffalexandre) [inline app/lib/database/model/Subscription.js:112]: Looks like it's not a necessary change, since it already exists on the model 😃  just undo and all fine

File: app/lib/database/model/migrations.js [hunk 11]
```diff
@@ -136,6 +136,7 @@ export default schemaMigrations({
 				addColumns({
 					table: 'subscriptions',
 					columns: [
+						{ name: 'join_code_required', type: 'boolean' },
```
Comment (djorkaeffalexandre) [inline app/lib/database/model/migrations.js:139]: You can also remove it

File: app/lib/database/schema/app.js [hunk 12]
```diff
@@ -50,6 +49,7 @@ export default appSchema({
 				{ name: 'served_by', type: 'string', isOptional: true },
 				{ name: 'livechat_data', type: 'string', isOptional: true },
 				{ name: 'tags', type: 'string', isOptional: true },
+				{ name: 'join_code_required', type: 'boolean' },
```
Comment (djorkaeffalexandre) [inline app/lib/database/schema/app.js:52]: Don't needed, it was already in the schema 😃

File: app/lib/methods/helpers/findSubscriptionsRooms.js [hunk 13]
```diff
@@ -50,6 +49,7 @@ export default async(subscriptions = [], rooms = []) => {
 			servedBy: s.servedBy,
 			livechatData: s.livechatData,
 			tags: s.tags,
+			joinCodeRequired: s.joinCodeRequired,
```
Comment (djorkaeffalexandre) [inline app/lib/methods/helpers/findSubscriptionsRooms.js:52]: Don't needed too

File: app/lib/methods/helpers/findSubscriptionsRooms.js [hunk 14]
```diff
@@ -79,6 +78,7 @@ export default async(subscriptions = [], rooms = []) => {
 			servedBy: r.servedBy,
 			livechatData: r.livechatData,
 			tags: r.tags,
+			joinCodeRequired: r.joinCodeRequired,
```
Comment (djorkaeffalexandre) [inline app/lib/methods/helpers/findSubscriptionsRooms.js:81]: +1

File: app/lib/methods/subscriptions/rooms.js [hunk 15]
```diff
@@ -82,6 +80,7 @@ const createOrUpdateSubscription = async(subscription, room) => {
 					servedBy: s.servedBy,
 					livechatData: s.livechatData,
 					tags: s.tags,
+					joinCodeRequired: s.joinCodeRequired,
```
Comment (djorkaeffalexandre) [inline app/lib/methods/subscriptions/rooms.js:83]: Just keep the older version :D

File: app/views/RoomView/index.js [hunk 16]
```diff
@@ -919,14 +921,31 @@ class RoomView extends React.Component {
...
 		}
 		if (!joined && !this.tmid) {
 			return (
 				<View style={styles.joinRoomContainer} key='room-view-join' testID='room-view-join'>
-					<Text accessibilityLabel={I18n.t('You_are_in_preview_mode')} style={[styles.previewMode, { color: themes[theme].titleText }]}>{I18n.t('You_are_in_preview_mode')}</Text>
+					{
+						joinCodeRequired
+							? (
+								<>
+									<Text accessibilityLabel={I18n.t('Insert_Join_Code')} style={[styles.previewMode, { color: themes[theme].titleText }]}>{I18n.t('Insert_Join_Code')}</Text>
```
Comment (djorkaeffalexandre) [inline app/views/RoomView/index.js:936]: You can use `<TextInput label={I18n.t('Insert_Join_Code')} ...`. :)

File: app/views/RoomView/index.js [hunk 17]
```diff
@@ -919,14 +921,31 @@ class RoomView extends React.Component {
...
+									<TextInput
+										returnKeyType='default'
+										placeholder={I18n.t('Join_Code')}
+										onChangeText={(value) => { this.setState({ joinCode: value }); }}
+										underlineColorAndroid='transparent'
+										containerStyle={styles.joinCodeInput}
```
Comment (djorkaeffalexandre) [inline app/views/RoomView/index.js:942]: pass `onSubmitEditing` prop calling `this.joinRoom` :)

File: app/views/RoomView/index.js [hunk 18]
```diff
@@ -919,14 +921,31 @@ class RoomView extends React.Component {
...
+										theme={theme}
+									/>
+								</>
```
Comment (djorkaeffalexandre) [inline app/views/RoomView/index.js:945]: Screen Shot 2020-10-07 at 12 55 05 PM
You can use a Input that cover `screen.width - 32` (margin horizontal = 16), it should be better

**Review by djorkaeffalexandre — CHANGES_REQUESTED** [review]
Almost there, nice work guys! 👏

File: app/views/RoomView/index.js (hunk 18 above)
Comment (DanMke) [reply app/views/RoomView/index.js:947]: taking the size of the screen did not work, the size of 200 in width

**Comment by DanMke** [comment]
Screen Shot 2020-10-07 at 23 54 49

**Review by djorkaeffalexandre — APPROVED** [review]
LGTM

**Comment by diegolmello** [comment]
@DanMke Can you update with develop? I want to merge it :)

**Comment by youssef-md** [comment]
> @DanMke Can you update with develop? I want to merge it :)

Done!

**Comment by diegolmello** [comment]
Do you guys have a Mac, so you can write e2e tests? (Otherwise, I might do it in the future)
This is the kind of feature that might break other things, so we should test it properly.
Thanks.

**Review by diegolmello — APPROVED** [review]

**Comment by diegolmello** [comment]
Merged. Thank you, guys! 👏 👏 👏
