### PR TITLE
[FIX] Avatar cache invalidation

### LINKED ISSUE #441: Avatar images doesn't refresh
Please can you test this app on Android devices. Avatar uploading doesn't work on android. I have installed the latest version from playstore but it is not uploading my avatar.

### LINKED ISSUE #1583: Avatar changes as username is changed in Profile View
- Your Rocket.Chat Experimental app version: 4.2.2.9999999
- Your Rocket.Chat server version: 2.5.0-develop open.rocket.chat
- Device (or Simulator) you're running with: Android P

This is a bug issue. As the gif shows, when we are changing the username, the avatar image gets changed simultaneously. 
ezgif com-crop(8)

### PR DESCRIPTION
**Pull request by djorkaeffalexandre**
@RocketChat/ReactNative

### Screenshots

Closes #441.
Closes #1583.

Screen Shot 2020-08-05 at 14 52 23
Screen Shot 2020-08-05 at 14 52 19
Screen Shot 2020-08-05 at 14 52 14
Screen Shot 2020-08-05 at 14 52 10

### CODE REVIEW

File: app/containers/Avatar/index.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+
+	const subscribeAvatar = async() => {
+		if (type === 'd') {
+			const db = database.active;
+			const usersCollection = db.collections.get('users');
+			try {
+				const [userRecord] = await usersCollection.query(Q.where('username', text)).fetch();
+				if (userRecord) {
+					const observable = userRecord.observe();
+					observable.subscribe((u) => {
```
Comment (djorkaeffalexandre) [inline app/containers/Avatar/index.js:21]: How we can handle the unsubscribe here?

File: app/presentation/RoomItem/index.js [hunk 2]
```diff
@@ -49,14 +51,35 @@ const RoomItemContainer = React.memo(({
...
 	}, [connected]);
 
+	const subscribeUser = async() => {
+		const db = database.active;
+		const usersCollection = db.collections.get('users');
+		try {
+			const [user] = await usersCollection.query(Q.where('username', Q.eq(username))).fetch();
+			if (user) {
+				const observable = user.observe();
+				observable.subscribe((u) => {
```
Comment (djorkaeffalexandre) [inline app/presentation/RoomItem/index.js:69]: unsubscribe?

File: app/containers/Avatar/index.js [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+import database from '../../lib/database';
+import { getUserSelector } from '../../selectors/login';
+import Component from './Avatar';
+
+const Avatar = React.memo(({ type, text, ...props }) => {
+	const [avatarETag, setAvatarETag] = useState();
+
+	useEffect(() => {
+		let subscription;
+		(async() => {
```
Comment (djorkaeffalexandre) [inline app/containers/Avatar/index.js:15]: Open to suggestions about how we can handle the unsubscribe without IIFE

File: app/containers/message/index.js [hunk 4]
```diff
@@ -69,14 +70,29 @@ class MessageContainer extends React.Component {
...
 			const observable = item.observe();
 			this.subscription = observable.subscribe(() => {
 				this.forceUpdate();
 			});
 		}
+
+		const db = database.active;
+		const usersCollection = db.collections.get('users');
+		try {
+			const user = await usersCollection.find(item.u._id);
```
Comment (djorkaeffalexandre) [inline app/containers/message/index.js:87]: I guess we can do a relationship between messages and users to don't need this find, but I don't know if it's better for us right now.
WDYT?

File: app/presentation/RoomItem/index.js [hunk 5]
```diff
@@ -57,13 +60,33 @@ const RoomItemContainer = React.memo(({
 	}, [connected]);
 
 	useEffect(() => {
+		let userSub;
+		if (item.t === 'd') {
+			(async() => {
+				const db = database.active;
+				const usersCollection = db.collections.get('users');
+				try {
+					const [user] = await usersCollection.query(Q.where('username', Q.eq(username))).fetch();
```
Comment (djorkaeffalexandre) [inline app/presentation/RoomItem/index.js:69]: WDYT about do a relationship between sub/user using username as a FK?

File: app/lib/database/model/Users.js [hunk 6]
```diff
@@ -0,0 +1,14 @@
+import { Model } from '@nozbe/watermelondb';
+import { field } from '@nozbe/watermelondb/decorators';
+
+export default class User extends Model {
```
Comment (djorkaeffalexandre) [inline app/lib/database/model/Users.js:4]: I've created this file as `Users`, since we already have a file called `User` on our models that refers to logged user.
I'm thinking about create a new folder to separate Models of the Default and Servers database.
WDYT?

File: app/containers/Avatar/index.js (hunk 3 above)
Comment (diegolmello) [reply app/containers/Avatar/index.js:15]: There's an issue here that `subscription` won't have a `unsubscribe` method even using IIFE.
Correct me if I'm wrong, but as this unnamed function doesn't `await`, return is called right away.

This could be rewritten as a normal function and being called right after, but the problem would remain.
```js
// taken from https://github.com/facebook/react/issues/14326#issuecomment-441680293
useEffect(() => {
  async function fetchMyAPI() {
    let url = 'http://something';
    let config = {};
    const response = await myFetch(url);
    console.log(response);
  }  

  fetchMyAPI();
}, []);
```

The issue here is that we need `subscription` to return a value on `useEffect`, so the unmount cleans everything.
If you switch to React.Component, this issue is gone easily :)

File: app/lib/database/model/Users.js (hunk 6 above)
Comment (diegolmello) [reply app/lib/database/model/Users.js:4]: I agree.

File: app/containers/message/index.js (hunk 4 above)
Comment (diegolmello) [reply app/containers/message/index.js:87]: Let's stick with this code as it doesn't hurt our users experience.

File: app/views/RoomView/Header/LeftButtons.js [hunk 7]
```diff
@@ -32,30 +32,22 @@ const LeftButtons = React.memo(({
...
-				style={styles.avatar}
-				userId={userId}
-				token={token}
-				onPress={onPress}
-			/>
-		);
-	}
-	return null;
+
+	return (
```
Comment (diegolmello) [inline app/views/RoomView/Header/LeftButtons.js:36]: IMO we should keep returning `null` here instead of relying to `Avatar` the responsibility

**Comment by shaheem-khanzada** [comment]
@diegolmello whats the status for this branch

**Comment by raza2022** [comment]
@djorkaeffalexandre @diegolmello any update on it, as I badly need this fix, let me also know if wanna any contribution in proposed solution/improvement

**Comment by djorkaeffalexandre** [comment]
Hey guys, it's planned to be part of 4.12 release. :)
Thanks.

**Review by diegolmello — APPROVED** [review]
LGTM
