### PR TITLE
[FIX] Unify upload check

### LINKED ISSUE #1167: Not able to upload images or files
- Your Rocket.Chat Experimental app version: 1.18.0
- Your Rocket.Chat server version: 1.3.2
- Device (or Simulator) you're running with: Moto G7 Power / Android 9

This may be a react issue but I cannot upload images or files because it believes the file is too large regardless of the server setting or the actual file size.

### PR DESCRIPTION
**Pull request by diegolmello**
@RocketChat/ReactNative

Closes #1167

### CODE REVIEW

File: app/containers/MessageBox/Recording.js [hunk 1]
```diff
@@ -102,7 +105,8 @@ export default class extends React.PureComponent {
 			this.recording = false;
 			const filePath = await AudioRecorder.stopRecording();
 			if (isAndroid) {
-				this.finishRecording(true, filePath);
+				const data = await RNFetchBlob.fs.stat(decodeURIComponent(filePath));
```
Comment (djorkaeffalexandre) [inline app/containers/MessageBox/Recording.js]: I think here is better to use `FileSystem.getInfoAsync(fileUri, options)`, I can't use it on Share Extension yet that's why I use `RNFetchBlob` but this code not is on Share Extension then you can use `Expo-File-System`.
