### PR TITLE
Message render performance

### LINKED ISSUE #905: [BUG] Wrong user agent on OAuth
WebView is showing weird content on OAuthView.
It seems to be introduced on #800.

### PR DESCRIPTION
**Pull request by diegolmello**
@RocketChat/ReactNative

Make Message leaner and faster to render.
I'm aiming to render RoomView instantly.
I'll use React.memo, React.context and move logic to RoomView.

Update:
If I manage to update RN, I'll use `useMemo` with React Context on user reducer instead of always passing down the tree.

Closes #905

### CODE REVIEW

File: app/containers/message/Reactions.js [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+		<View style={styles.reactionContainer}>
+			<CustomIcon name='add-reaction' size={21} style={styles.addReaction} />
+		</View>
+	</Touchable>
+));
+
+const Reaction = React.memo(({
+	reaction, user, onReactionLongPress, onReactionPress, baseUrl, getCustomEmoji
+}) => {
+	const reacted = reaction.usernames.findIndex(item => item === user.username) !== -1;
```
Comment (IlarionHalushka) [inline app/containers/message/Reactions.js]: unnecessary `!== -1`

File: app/containers/message/Reactions.js [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+					onReactionLongPress={onReactionLongPress}
+					onReactionPress={onReactionPress}
+					getCustomEmoji={getCustomEmoji}
+				/>
+			))}
+			<AddReaction toggleReactionPicker={toggleReactionPicker} />
+		</View>
+	);
+});
+// FIXME: can't compare because it's a Realm object (it may be fixed by JSON.parse(JSON.stringify(reactions)))
```
Comment (IlarionHalushka) [inline app/containers/message/Reactions.js]: TODO for future?

File: app/containers/message/Reply.js [hunk 3]
```diff
@@ -69,98 +70,130 @@ const styles = StyleSheet.create({
...
-	}
-	if (attachment.type === 'file') {
-		url = `${ baseUrl }${ url }?rc_uid=${ user.id }&rc_token=${ user.token }`;
+const Title = React.memo(({ attachment, timeFormat }) => {
+	if (!attachment.author_name) {
+		return null;
 	}
-	openLink(url);
-};
+	const time = attachment.ts ? moment(attachment.ts).format(timeFormat) : null;
```
Comment (IlarionHalushka) [inline app/containers/message/Reply.js]: why not `&&`?

File: app/containers/message/Thread.js [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+
+const Thread = React.memo(({
+	msg, tcount, tlm, customThreadTimeFormat
+}) => {
+	if (!tlm) {
+		return null;
+	}
+
+	const time = formatLastMessage(tlm, customThreadTimeFormat);
+	const buttonText = formatMessageCount(tcount, 'thread');
```
Comment (IlarionHalushka) [inline app/containers/message/Thread.js]: add to `./constants` `message.type.THREAD`

File: app/views/MessagesView/index.js [hunk 5]
```diff
@@ -190,6 +194,15 @@ export default class MessagesView extends LoggedView {
 		}
 	}
 
+	onOpenFileModal = (attachment) => {
+		console.log('TCL: onOpenFileModal -> attachment', attachment);
```
Comment (IlarionHalushka) [inline app/views/MessagesView/index.js]: remove console.log

File: app/views/RoomsListView/index.js [hunk 6]
```diff
@@ -311,6 +316,15 @@ export default class RoomsListView extends LoggedView {
 		}
 	}
 
+	// Just for tests purposes
```
Comment (IlarionHalushka) [inline app/views/RoomsListView/index.js]: should it be removed or it's for e2e tests?

File: storybook/stories/Message.js [hunk 7]
```diff
@@ -24,19 +24,30 @@ const author = {
 	username: 'diego.mello'
 };
 const baseUrl = 'https://open.rocket.chat';
-const customEmojis = { react_rocket: 'png', nyan_rocket: 'png', marioparty: 'gif' };
 const date = new Date(2017, 10, 10, 10);
 const longText = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.';
 
+const getCustomEmoji = (content) => {
+	if (content === 'marioparty') {
```
Comment (IlarionHalushka) [inline storybook/stories/Message.js]: I would prefer using `const customEmoji = { marioparty: {...}, react_rocket: {...}, nyan_rocket: {...} }[content];      return customEmoji;`

File: app/containers/FileModal.js [hunk 8]
```diff
@@ -0,0 +1,113 @@
...
+
+const ModalContent = React.memo(({ attachment, onClose }) => {
+	if (attachment && attachment.image_url) {
+		const url = RocketChat.formatAttachmentUrl(attachment.image_url);
+		return (
+			<SafeAreaView style={styles.safeArea}>
+				<TouchableWithoutFeedback onPress={onClose}>
+					<View style={styles.titleContainer}>
+						<Text style={styles.title}>{attachment.title}</Text>
+						{attachment.description ? <Text style={styles.description}>{attachment.description}</Text> : null}
```
[the remark this answers is not in the document]
Comment (diegolmello) [reply app/containers/FileModal.js]: I'm not sure new JSC, but old ones used to crash.
Related: https://github.com/react-native-community/discussions-and-proposals/issues/64#issuecomment-444778851 and https://github.com/react-native-community/discussions-and-proposals/issues/64#issuecomment-444938376

File: app/containers/ReactionsModal.js [hunk 9]
```diff
@@ -0,0 +1,152 @@
...
+	}
+});
+const standardEmojiStyle = { fontSize: 20 };
+const customEmojiStyle = { width: 20, height: 20 };
+
+const Item = React.memo(({ item, user, baseUrl }) => {
+	const count = item.usernames.length;
+	let usernames = item.usernames.slice(0, 3)
+		.map(username => (username === user.username ? I18n.t('you') : username)).join(', ');
+	if (count > 3) {
```
[the remark this answers is not in the document]
Comment (diegolmello) [reply app/containers/ReactionsModal.js]: ReactionsModal logic was just moved around.
We'll have to change it in near future to show all reacted users.
Currently, it's showing only three people + number of the rest.
We should be able to show all of them :P

File: app/containers/message/Attachments.js [hunk 10]
```diff
@@ -0,0 +1,44 @@
...
+const Attachments = React.memo(({
+	attachments, timeFormat, user, baseUrl, useMarkdown, onOpenFileModal, getCustomEmoji
+}) => {
+	if (!attachments || attachments.length === 0) {
+		return null;
+	}
+
+	return attachments.map((file, index) => {
+		if (file.image_url) {
+			return <Image key={file.image_url} file={file} user={user} baseUrl={baseUrl} onOpenFileModal={onOpenFileModal} getCustomEmoji={getCustomEmoji} useMarkdown={useMarkdown} />;
```
[the remark this answers is not in the document]
Comment (diegolmello) [reply app/containers/message/Attachments.js]: Nope.
I'll refactor soon with React.context in order to stop passing these props down the tree.
I didn't do it yet because I need `useMemo`.
Read this: https://kentcdodds.com/blog/how-to-optimize-your-context-value

Also: make sure to read all of Kent's posts. He's an awesome hooman :)

File: app/containers/message/Audio.js [hunk 11]
```diff
@@ -120,22 +144,26 @@ export default class Audio extends React.Component {
 		});
 	}
 
-	getDuration = () => {
+	get duration() {
 		const { duration } = this.state;
 		return formatTime(duration);
 	}
 
+	setRef = ref => this.player = ref;
```
[the remark this answers is not in the document]
Comment (diegolmello) [reply app/containers/message/Audio.js]: I'm not convinced what's best... I'll leave it as it is for now.

File: app/containers/message/Discussion.js [hunk 12]
```diff
@@ -0,0 +1,57 @@
...
+				</Touchable>
+				<Text style={styles.time}>{time}</Text>
+			</View>
+		</React.Fragment>
+	);
+}, (prevProps, nextProps) => {
+	if (prevProps.msg !== nextProps.msg) {
+		return false;
+	}
+	if (prevProps.dount !== nextProps.dount) {
```
[the remark this answers is not in the document]
Comment (diegolmello) [reply app/containers/message/Discussion.js]: Huge catch! :)

File: app/containers/FileModal.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (IlarionHalushka) [reply app/containers/FileModal.js]: agree about the case when `{number && <Text />}` and the `number === 0` ==>> crash

[the remark this answers is not in the document]
Comment (IlarionHalushka) [reply app/containers/FileModal.js]: with empty strings or undefined or null works ok (as I remember), but better for safety reasons it's better to use ternary operator 👍

File: app/views/RoomsListView/index.js (hunk 6 above)
Comment (diegolmello) [reply app/views/RoomsListView/index.js]: It'll be removed before merge. It's just a test to see if markdown is taking too much.

File: app/containers/message/Audio.js [hunk 13]
```diff
@@ -56,20 +56,44 @@ const formatTime = seconds => moment.utc(seconds * 1000).format('mm:ss');
...
+const Button = React.memo(({ paused, onPress }) => (
+	<Touchable
+		style={styles.playPauseButton}
+		onPress={onPress}
+		hitSlop={BUTTON_HIT_SLOP}
+		background={Touchable.SelectableBackgroundBorderless()}
+	>
+		{
+			paused
+				? <CustomIcon name='play' size={36} style={styles.playPauseImage} />
```
[the remark this answers is not in the document]
Comment (diegolmello) [reply app/containers/message/Audio.js]: 👏👏👏

File: app/containers/message/Reactions.js (hunk 1 above)
Comment (diegolmello) [reply app/containers/message/Reactions.js]: It's is necessary.
I want to know if it IS found.
`findIndex` returns `-1` when not found.
`-1` is not falsey.
