### PR TITLE
[FIX] Messagebox missing style for text color

### LINKED ISSUE #2784: [IMPROVEMENT] 'New Message' text should be greyed out
### Description:

In the rocket chat iOS app, the 'New Message' placeholder text is the same color as regular text, making it hard to distinguish as a placeholder.  The text should be greyed out, similar to the desktop app. 

### Environment Information:

- Rocket.Chat Server Version: 3.9.4
- Rocket.Chat App Version: 3.12.1
- Device Name: iPhone 11
- OS Version: iOS 14

### Expected behavior:

Placeholder text has different text color than regular text

### Actual behavior:

Placeholder text color is the same as regular text

### PR DESCRIPTION
**Pull request by yash-rajpal**
## Proposed changes

To do so, changed auxiliaryTintColor for dark theme, so all components using this auxiliary tint color are now little greyed for dark theme.
## Issue(s)	

fixes #2784 
## Screenshots
##Before
image

##After
image

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

I understand all components using this colour would be greyed out a little, If its not okay then we can make a new color setting for Placeholder, or use "auxiliaryText" color for Placeholder.

### CODE REVIEW

**Comment by yash-rajpal** [comment]
@diegolmello Please tell what should be done?
Thanks

**Review by diegolmello — CHANGES_REQUESTED** [review]
Correct fix should be to add `bodyText` color to textBoxInput on Messagebox's styles

**Comment by yash-rajpal** [comment]
@diegolmello Please check.

File: app/containers/MessageBox/index.js [hunk 1]
```diff
@@ -932,7 +932,7 @@ class MessageBox extends Component {
 					keyboardType='twitter'
 					blurOnSubmit={false}
 					placeholder={I18n.t('New_Message')}
-					placeholderTextColor={themes[theme].auxiliaryTintColor}
+					placeholderTextColor={themes[theme].bodyText}
```
Comment (diegolmello) [inline app/containers/MessageBox/index.js:935]: This line was correct.
You just have to add this theme [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/containers/MessageBox/styles.js#L19) to `color`.

Try adding `color: 'red',` there and you'll see.

**Review by diegolmello — CHANGES_REQUESTED** [review]

File: app/containers/MessageBox/index.js (hunk 1 above)
Comment (yash-rajpal) [reply app/containers/MessageBox/index.js:935]: So you are saying PlaceHolderText would be auxiliaryTintColor and Color of text message should be bodyText?

File: app/containers/MessageBox/index.js [hunk 2]
```diff
@@ -927,7 +927,7 @@ class MessageBox extends Component {
 				/>
 				<TextInput
 					ref={component => this.component = component}
-					style={styles.textBoxInput}
+					style={{ ...styles.textBoxInput, color: themes[theme].bodyText }}
```
Comment (diegolmello) [inline app/containers/MessageBox/index.js:930]: Use array instead of object.

```suggestion
					style={[styles.textBoxInput, { color: themes[theme].bodyText }]}
```

Comment (yash-rajpal) [reply app/containers/MessageBox/index.js]: Done,

**Review by diegolmello — APPROVED** [review]
LGTM

**Comment by yash-rajpal** [comment]
Thanks @diegolmello.
