### PR TITLE
[FIX] MultiSelect Keyboard behavior (Android)

### LINKED ISSUE #1966: [BUG] MultiSelect keyboard behavior (Android)
- Your Rocket.Chat Experimental app version: 4.6.0.9
- Your Rocket.Chat server version: 3.1.0-rc.6
- Device (or Simulator) you're running with: Android P Samsung Galaxy J6

As the following Gif shows, the input boxes for selecting channel and users don't work properly. The modal showing the input box goes out of screen when keyboard is opened. This creates problem in typing. Also when the modal is closed, the screen remains out of focus
ezgif com-resize

### PR DESCRIPTION
**Pull request by Prateek93a**
@RocketChat/ReactNative

Closes #1966 

As the Gif shows, the issue is fixed, it was related to `KeyboardAvoidingView` . Found a similar [ issue](https://stackoverflow.com/questions/43854912/react-native-keyboardavoidingview-covers-last-text-input) related to `KeyboardAvoidingView`, that helped fix it.
ezgif com-crop(9)

### CODE REVIEW

File: app/containers/UIKit/MultiSelect/index.js [hunk 1]
```diff
@@ -26,6 +26,8 @@ const ANIMATION_PROPS = {
 };
 const animatedValue = new Animated.Value(0);
 
+const behavior = Platform.OS === 'ios' ? 'padding' : null;
```
Comment (djorkaeffalexandre) [inline app/containers/UIKit/MultiSelect/index.js:29]: @Prateek93a use our own const `isIOS`.

Comment (Prateek93a) [reply app/containers/UIKit/MultiSelect/index.js]: Done
