### PR TITLE
[FIX] Read only channel/broadcast

### LINKED ISSUE #1025: Cannot write into "read only group" as owner
- Your Rocket.Chat Experimental app version: 1.15.0
- Your Rocket.Chat server version: 1.2.1
- Device (or Simulator) you're running with: Android 7.1

You cannot write into a read only group even if you are an admin or owner of the group.

Steps to reproduce (iOS):
* Open a channel "read only" as owner
* Try message actions on any message

### PR DESCRIPTION
**Pull request by djorkaeffalexandre**
@RocketChat/ReactNative

Closes #1025.

This pr fixes 3 problems:
- [X] Moderator should be able to write on readOnly channels.
- [X] When a `read-only` channel is created, messageBox isn't showed.
- [X] When open message Actions on read-only channel messageBox disappear.

### CODE REVIEW

**Comment by diegolmello** [comment]
@djorkaeffalexandre 
Mar-30-2020 09-43-42

I'm not hiding the keyboard.
It seems the subscription is updated quickly and hides it.

File: app/utils/room.js [hunk 1]
```diff
@@ -2,12 +2,15 @@ import moment from 'moment';
 
 import I18n from '../i18n';
 
-export const isOwner = room => room && room.roles && room.roles.length && !!room.roles.find(role => role === 'owner');
+export const isOwnerOrModerator = room => room && room.roles && room.roles.length && !!room.roles.find(role => role === 'owner' || role === 'moderator');
```
Comment (diegolmello) [inline app/utils/room.js]: You should check `post-readonly` permission.
